<?php

/**
 * @file
 * Main code.
 *
 * @author
 * Name: Nikita Malyshev
 * Web: http://niklan.net
 * Email: hello@niklan.net
 */

/**
 * Implements hook_menu().
 */
function entityform_ctools_menu() {
  // @TODO handle to editing existing entityforms in ctools.
  $items['entityform_ctools/%ctools_js/add/%'] = array(
    'title' => 'Entityform Ctools Page',
    'page callback' => 'entityform_ctools_page_callback',
    'page arguments' => array(3, 1),
    // @TODO add callback
    'access callback' => TRUE,
    'delivery callback' => 'ajax_deliver',
    'theme callback' => 'ajax_base_page_theme',
  );

  $items['entityform_ctools/ajax'] = array(
    'title' => 'Entityform Ajax Callback',
    'page callback' => 'entityform_ctools_ajax_callback',
    'access callback' => TRUE,
    'delivery callback' => 'ajax_deliver',
    'theme callback' => 'ajax_base_page_theme',
  );

  return $items;
}

/**
 * Include modal libraries.
 */
function _entityform_ctools_include_modal() {
  static $added = FALSE;
  if ($added == FALSE) {
    $added = TRUE;

    // Include the CTools tools that we need.
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();

    // @see http://cgit.drupalcode.org/ctools/tree/help/modal.html
    $style = array(
      'entityform' => array(
        'modalSize' => array(
          // fixed or scale
          'type' => 'fixed',
          // Npx or 0-1 as percentage, where 0.1 - 10%
          'width' => '320px',
          // Npx or 0-1 as percentage.
          'height' => 'auto',
          'addWidth' => '0',
          'addHeight' => '0',
          'contentRight' => '25',
          'contentBottom' => '0',
        ),
        'modalTheme' => 'entityform_ctools_modal',
        'throbberTheme' => 'entityform_ctools_throbber',
        'modalClass' => 'entityform',
        // This is css array will apply automatically.
        'modalOptions' => array(),
        // show, fadeIn or slideDown
        'animation' => 'show',
        // slow, medium or fast
        'animationSpeed' => 'fast',
        'closeText' => 'Закрыть ❌',
        'closeImage' => '',
        // @TODO translate
        'loadingText' => 'Секундочку, форма загружается…',
        'throbber' => theme('image', array(
          'path' => ctools_image_path('throbber.gif', 'entityform_ctools'),
          'alt' => t('Loading...'),
          'title' => t('Loading')
        )),
      ),
    );

    drupal_add_js($style, 'setting');
    ctools_add_js('entityform-modal', 'entityform_ctools');
  }
}

/**
 * @param null $js
 * @return array
 */
function entityform_ctools_page_callback($entityform_name, $js = NULL) {
  ctools_include('entityform.admin', 'entityform', '');
  ctools_include('modal');
  ctools_include('ajax');

  $entityform_types_objects = entityform_get_types();
  // If disabled JavaScript.
  if (!$js) {
    $entityform_info = $entityform_types_objects[$entityform_name];
    if (isset($entityform_info->paths['submit']['alias'])) {
      $redirect_path = $entityform_info->paths['submit']['alias'];
    }
    else {
      $redirect_path = 'eform/submit/' . $entityform_name;
    }
    drupal_goto($redirect_path, array(), 301);
  }

  $title = $entityform_types_objects[$entityform_name]->label;
  if (module_exists('entityform_i18n')) {
    $title = $entityform_types_objects[$entityform_name]->getTranslation('label');
  }

  $form_state = array(
    'title' => $title,
    'ajax' => TRUE,
    'build_info' => array(
      'args' => array(
        entityform_empty_load($entityform_name),
        'submit',
        'embedded'
      ),
    ),
  );

  $commands = ctools_modal_form_wrapper($entityform_name . '_entityform_edit_form', $form_state);
  if (!empty($form_state['executed'])) {
    $commands = array();
    $commands[] = ajax_command_prepend('#modal-content', theme('status_messages'));
  }

  // hook_entityform_ctools_FORM_ID_commands_alter().
  drupal_alter('entityform_ctools_' . $entityform_name . '_commands', $commands, $form_state);
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Creates ctools link form creating new entityform in modal.
 */
function entityform_ctools_add_link($text, $entityform_name, $theme = '', $options = array()) {
  _entityform_ctools_include_modal();
  drupal_add_library('system', 'drupal.ajax');
  $default_options = array(
    'html' => TRUE,
    'attributes' => array(
      'class' => array('ctools-use-modal', 'ctools-modal-' . $theme),
    ),
  );
  return l($text, 'entityform_ctools/nojs/add/' . $entityform_name, array_merge_recursive($default_options, $options));
}

/**
 * Callback for ajax submissions of entityform.
 */
function entityform_ctools_ajax_callback() {
  module_load_include('inc', 'entityform', 'entityform.admin');
  list($form, $form_state) = ajax_get_form();
  drupal_process_form($form['#form_id'], $form, $form_state);
  $action_path = 'entityform_ctools/ajax';
  $form['#action'] = $action_path;
  $form['actions']['submit']['#ajax'] = array('path' => $action_path);
  $form['actions']['submit']['#attributes']['class'][] = 'use-ajax-submit';
  $output = drupal_render($form);

  $form_html_id = '#' . $form_state['complete form']['#id'];

  $commands = array();
  if ($messages = theme('status_messages')) {
    $commands[] = ajax_command_html('#' . $form['#form_id'] . '-messages', $messages);
  }
  $commands[] = ajax_command_replace($form_html_id, $output);

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Get entityform form with ajax submit handler.
 */
function entityform_ctools_get_ajax_form($entityform_name) {
  module_load_include('inc', 'entityform', 'entityform.admin');
  drupal_add_library('system', 'jquery.form');
  drupal_add_library('system', 'drupal.form');
  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'drupal.progress');

  $action_path = 'entityform_ctools/ajax';
  $form_id = $entityform_name . '_entityform_edit_form';
  $form_state = array(
    'ajax' => TRUE,
    'inline_ajax' => TRUE,
    'rebuild' => FALSE,
    'cache' => TRUE,
    'build_info' => array(
      'args' => array(
        entityform_empty_load($entityform_name),
        'submit',
        'embedded'
      ),
    ),
  );

  $output = drupal_build_form($form_id, $form_state);
  $output['#action'] = $action_path;
  $output['actions']['submit']['#ajax'] = array('path' => $action_path);
  $output['actions']['submit']['#attributes']['class'][] = 'use-ajax-submit';
  $messages = '<div id="' . $form_id . '-messages"></div>';
  $output = drupal_render($output);
  return $messages . $output;
}
