<?php

/**
 * @file
 * Main code.
 *
 * @author
 * Name: Nikita Malyshev
 * Web: http://niklan.net
 * Email: hello@niklan.net
 */

/**
 * Implements hook_menu().
 */
function entityform_ctools_menu() {
  // @TODO handle to editing existing entityforms in ctools.
  $items['entityform_ctools/%/add/%'] = array(
    'title' => 'Entityform Ctools Page',
    'page callback' => 'entityform_ctools_page_callback',
    'page arguments' => array(3, 1),
    // @TODO add callback
    'access callback' => TRUE,
    'delivery callback' => 'ajax_deliver',
    'theme callback' => 'ajax_base_page_theme',
  );

  return $items;
}

/**
 * Include modal libraries.
 */
function _entityform_ctools_include_modal() {
  static $added = FALSE;
  if ($added == FALSE) {
    $added = TRUE;

    // Include the CTools tools that we need.
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();

    $style = array(
      'default' => array(
        'modalSize' => array(
          // fixed or scale
          'type' => 'scale',
          'width' => 'auto',
          'height' => 'auto',
        ),
        'modalOptions' => array(
          'opacity' => (float) 0.4,
          'background-color' => 'rgb(62, 71, 87)',
        ),
        'closeText' => '',
        // @TODO translate
        'loadingText' => 'Секундочку, форма загружается…',
        'animation' => 'fadeIn',
        'animationSpeed' => 'fast',
      ),
    );

    drupal_add_js($style, 'setting');
  }
}

/**
 * @param null $js
 * @return array
 */
function entityform_ctools_page_callback($entityform_name, $js = NULL) {
  // If disabled JavaScript.
  if (!$js) {
    // @TODO move to entityform submission page.
    drupal_goto('<front>');
  }

  ctools_include('entityform.admin', 'entityform', '');
  ctools_include('modal');
  ctools_include('ajax');

  $entityform_types_objects = entityform_get_types();

  $form_state = array(
    'title' => $entityform_types_objects[$entityform_name]->label,
    'ajax' => TRUE,
    'build_info' => array(
      'args' => array(
        entityform_empty_load($entityform_name),
        'submit',
        'embedded'
      ),
    ),
  );

  $commands = ctools_modal_form_wrapper($entityform_name . '_entityform_edit_form', $form_state);

  if (!empty($form_state['executed'])) {
    // @TODO add hook for possibility to change commands.
    $commands = array();
    $commands[] = ajax_command_prepend('#modal-content', theme('status_messages'));
    drupal_alter('entityform_ctools_' . $entityform_name . '_executed_commands', $commands, $form_state);
  }

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Creates ctools link form creating new entityform in modal.
 */
function entityform_ctools_add_link($text, $entityform_name, $theme = '', $options = array()) {
  _entityform_ctools_include_modal();
  drupal_add_library('system', 'drupal.ajax');
  $default_options = array(
    'html' => TRUE,
    'attributes' => array(
      'class' => array('use-ajax', 'ctools-use-modal', $theme),
    ),
  );
  return l($text, 'entityform_ctools/nojs/add/' . $entityform_name, array_merge_recursive($default_options, $options));
}

/**
 * Implements hook_form_alter().
 */
function entityform_ctools_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#entity_type']) && isset($form['#bundle']) && !(arg(0) == 'admin')) {
    if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
      // Call alter for ajax called entityform.
      drupal_alter($form['#bundle'] . '_entityform_ctools', $form, $form_state);
    }
  }
}
